# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(default=30, verbose_name='年龄'),
        ),
    ]
