# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_teacher_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(default=30, null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='click_nums',
            field=models.IntegerField(default=0, null=True, verbose_name='点击量'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='fav_nums',
            field=models.IntegerField(default=0, null=True, verbose_name='收藏量'),
        ),
    ]
