# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20170905_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='click_nums',
            field=models.IntegerField(default=0, null=True, verbose_name='点击量'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='fav_nums',
            field=models.IntegerField(default=0, null=True, verbose_name='收藏量'),
        ),
    ]
