# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 14:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20170829_1045'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourscComments',
            new_name='CourseComments',
        ),
    ]
