# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_usersignup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersignup',
            name='course',
        ),
        migrations.RemoveField(
            model_name='usersignup',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserSignUp',
        ),
    ]
