# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher_say',
            field=models.CharField(default='学习改变命运', max_length=300, verbose_name='老师带话'),
        ),
        migrations.AddField(
            model_name='course',
            name='you_need_know',
            field=models.CharField(default='人要没决心，一事无成！', max_length=1000, verbose_name='你需要知道'),
        ),
    ]
