# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20170829_1819'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vedio',
            new_name='Video',
        ),
    ]
