# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 14:34
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_course_is_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='desc',
            field=DjangoUeditor.models.UEditorField(verbose_name='课程简介'),
        ),
    ]
