# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', '注册'), ('forget', '忘记密码'), ('changeeamil', '更换邮箱')], max_length=15, verbose_name='发送方式'),
        ),
    ]
